routes/web.php
<?php

//Front routes
Route::get('/', [
  'uses' => 'FrontController@index',
  'as' => 'front.index'
]);

Route::get('/contact', function(){
    return view('front.contact');
});

Route::get('/work-with-us', function(){
    return view('work_with_us');
});

Route::post('/work-with-us', 'FrontController@work_with_us');

Route::get('/affiliations', function(){
    return view('coming_soon');
});

Route::post('/affiliations', 'FrontController@affiliations');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('public', function(){
	return view('public');
});

Route::get('formulario', 'FileController@index');

Route::post('public', 'FileController@store');

//Panel de ADMON//
Route::get('/ls', 'Auth\RegisterController@ruta');

// E-mail verification
Route::get('/register/verify/{code}', 'Auth\RegisterController@verify');

Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function (){
	//USER//
	Route::resource('users','UsersController');
	Route::get('users/{id}/destroy', [
            'uses' => 'UsersController@destroy',
            'as' => 'admin.users.destroy'
        ]);

	//COUNTRY//
	Route::resource('countries','CountryController');
	Route::get('countries/{id}/destroy', [
            'uses' => 'CountryController@destroy',
            'as' => 'admin.countries.destroy'
        ]);

	//DEPARTMENT//
	Route::resource('departments','DepartmentController');
	Route::get('departments/{id}/destroy', [
            'uses' => 'DepartmentController@destroy',
            'as' => 'admin.departments.destroy'
        ]);

	//CITY//
	Route::resource('cities','CityController');
	Route::get('cities/{id}/destroy', [
            'uses' => 'CityController@destroy',
            'as' => 'admin.cities.destroy'
        ]);
});

//CUSTOMER//
Route::resource('customers','CustomerController');
	Route::get('customers/{id}/destroy', [
            'uses' => 'CustomerController@destroy',
            'as' => 'customers.destroy'
        ]);

//AFILIADO//
Route::resource('afiliados','AfiliadosController');
    Route::get('afiliados/{id}/destroy', [
            'uses' => 'AfiliadosController@destroy',
            'as' => 'afiliados.destroy'
        ]);

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}"">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Sistema</title>
    <!-- Styles -->

  <link rel="stylesheet" href="/css/session/materialdesignicons.min.css">
  <link rel="stylesheet" href="/css/session/vendor.bundle.base.css">
  <link rel="stylesheet" href="/css/session/vendor.bundle.addons.css">

  <!-- Theme Style -->
  <link rel="stylesheet" href="/css/session/style.css">

</head>
<body>
  <div class="container-scroller">
    @include('layouts.navbar')
    <div class="container-fluid page-body-wrapper">
      @include('layouts.sidebar')
      <div class="main-panel">

        <div class="content-wrapper">
          @include('flash::message')
          @yield('content') 
        </div>

        @include('layouts.footer')
      </div>
    </div>
  </div>
  
  <!-- Scripts -->
  <script src="/js/session/vendor.bundle.base.js"></script>
  <script src="/js/session/vendor.bundle.addons.js"></script>
  <script src="/js/session/off-canvas.js"></script>
  <script src="/js/session/misc.js"></script>
  <script src="/js/session/dashboard.js"></script>
  <script>
      $('div.alert').not('.alert-important').delay(3000).fadeOut(350);
  </script>
</body>
</html>

resources/views/layouts/footer.blade.php
<footer class="footer">
  <div class="container-fluid clearfix">
    <span class="text-muted d-block text-center text-sm-left d-sm-inline-block">Copyright © 2018
      <a href="#" target="_blank">Bit3</a>. All rights reserved.</span>
  </div>
</footer>

resources/views/layouts/navbar.blade.php
<nav class="navbar default-layout col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
	<div class="text-center navbar-brand-wrapper d-flex align-items-top justify-content-center">
		<a href="#" class="navbar-brand brand-logo">
			<img src="https://mdbootstrap.com/img/logo/mdb-transparent.png" alt="logo" />
		</a>
		<a href="" class="navbar-brand brand-logo-mini">
			<img src="" alt="logo" />
		</a>
	</div>
	<div class="navbar-menu-wrapper d-flex align-items-center">
		<ul class="navbar-nav navbar-nav-right">
			<li class="nav-item dropdown d-none d-xl-inline-block">
				<a class="nav-link dropdown-toggle" id="UserDropdown" href="#" data-toggle="dropdown" aria-expanded="false">
					<span class="profile-text">
						{{ Auth::user()->name }}
					</span>
					<img src="https://mdbootstrap.com/img/Photos/Others/forest-sm.jpg" alt="" class="img-xs rounded-circle" alt="Profile image">
				</a>
				<div class="dropdown-menu dropdown-menu-right navbar-dropdown" aria-labelledby="UserDropdown">
					<a class="dropdown-item mt-2">
            Manage Accounts
          </a>
          <a class="dropdown-item">
            Change Password
          </a>
          <a class="dropdown-item">
            Check Inbox
          </a>
					<a href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();" class="dropdown-item">
						Sign Out
					</a>
					<form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
	            {{ csrf_field() }}
	        </form>
				</div>
			</li>
		</ul>
		<button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
      <span class="mdi mdi-menu"></span>
    </button>
	</div>
</nav>

resources/views/layouts/sidebar.blade.php
<nav class="sidebar sidebar-offcanvas" id="sidebar">
  <ul class="nav">
    <li class="nav-item">
      <a class="nav-link" href="/home">
        <i class="menu-icon mdi mdi-television"></i>
        <span class="menu-title">Dashboard</span>
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/afiliados">
        <i class="menu-icon mdi mdi-account-multiple"></i>
        <span class="menu-title">Afiliados</span>
      </a>
    </li>
    @if(Auth::user()->admin())
    <li class="nav-item">
      <a class="nav-link" href="{{ route('users.index') }}">
        <i class="menu-icon mdi mdi-account-multiple"></i>
        <span class="menu-title">Usuarios</span>
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link" data-toggle="collapse" href="#auth" aria-expanded="false" aria-controls="auth">
        <i class="menu-icon mdi mdi-settings"></i>
        <span class="menu-title">Configuración</span>
        <i class="menu-arrow"></i>
      </a>
      <div class="collapse" id="auth">
        <ul class="nav flex-column sub-menu">
          <li class="nav-item">
            <a class="nav-link" href="{{ route('countries.index') }}"> Paises </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ route('departments.index') }}"> Departamentos </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ route('cities.index') }}"> Ciudades </a>
          </li>
        </ul>
      </div>
    </li>
    @endif
  </ul>
</nav>